spring:
 datasource:
  url: jdbc:mysql://localhost:3307/db2
  username: root
  password: root
  
 jpa:
  hibernate:
   dialect: org.hibernate.dialect.MySQLDialect
   ddl-auto: update
   format_sql: true